# permissions for end users to edit helloworldren.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworld-editor-role
rules:
- apiGroups:
  - webapp.examples.kubebuilder.io
  resources:
  - helloworldren
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.examples.kubebuilder.io
  resources:
  - helloworldren/status
  verbs:
  - get
